description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  firebase_core: "^1.0.1"
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.4
  google_sign_in: ^5.0.0
  flutter_signin_button: ^1.1.0
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
