import 'package:flutter/material.dart';
import 'package:flutterapp/appmovilapp/generatedloginviewwidget/generated/GeneratedIPhoneXRXSMax113Widget.dart';

/* Frame Log In view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogInviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -738.0,
                top: -89.0,
                right: null,
                bottom: null,
                width: 2035.0,
                height: 1017.5,
                child: GeneratedIPhoneXRXSMax113Widget(),
              )
            ]),
      ),
    ));
  }
}
