import 'package:flutter/material.dart';
import 'package:flutterapp/appmovilapp/generateddetailsplaceviewwidget/generated/GeneratedIPhoneXRXSMax117Widget.dart';

/* Frame Details place view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailsplaceviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: -22.0,
                top: -12.0,
                right: null,
                bottom: null,
                width: 515.0,
                height: 959.0,
                child: GeneratedIPhoneXRXSMax117Widget(),
              )
            ]),
      ),
    ));
  }
}
