import 'package:flutter/material.dart';
import 'package:flutterapp/appmovilapp/generateddetailsplaceviewwidget/generated/GeneratedIPhoneXRXSMax117Widget.dart';

/* Frame Details place view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailsplaceviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                child: GeneratedIPhoneXRXSMax117Widget(),
              )
            ]),
      ),
    ));
  }
}
