import 'package:flutter/material.dart';
import 'package:flutterapp/appmovilapp/generateddetailsplaceviewwidget/generated/GeneratedIPhoneXRXSMax117Widget.dart';

/* Frame Details place view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailsplaceviewWidget extends StatefulWidget {
  final ValueChanged<bool> setFalse;

  const GeneratedDetailsplaceviewWidget({Key key, this.setFalse})
      : super(key: key);

  @override
  GeneratedDetailsplaceviewWidgetState createState() =>
      GeneratedDetailsplaceviewWidgetState();
}

class GeneratedDetailsplaceviewWidgetState
    extends State<GeneratedDetailsplaceviewWidget> {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            child: GeneratedIPhoneXRXSMax117Widget(setFalse: widget.setFalse),
          ),
        ));
  }
}
